// packages/vue/src/ContrastButton.vue
<template>
  <button :style="style" :class="className" @click="toggleContrast">
    {{ text }}
  </button>
</template>

<script setup lang="ts">
import { A11yManager } from '@a11y-buttons/core';
import '@a11y-buttons/core/src/styles/contrast.css';

const props = defineProps({
  text: { type: String, default: 'Modo Contraste' },
  style: { type: Object, default: () => ({}) },
  className: { type: String, default: '' }
});

const a11yManager = new A11yManager();

function toggleContrast() {
  a11yManager.toggleContrast();
}
</script>

// packages/react/src/ContrastButton.tsx
import React from 'react';
import {A11yManager} from '@a11y-buttons/core';
import '@a11y-buttons/core/src/styles/contrast.css';

interface ContrastButtonProps {
  text?: string;
  style?: React.CSSProperties;
  className?: string;
}

const a11yManager = new A11yManager();

export const ContrastButton: React.FC<ContrastButtonProps> = ({
  text = 'Alto Contraste',
  style,
  className,
}) => {
  return (
    <button onClick={() => a11yManager.toggleContrast()} style={style} className={className}>
      {text}
    </button>
  )
}
