// packages/react/src/IncreaseFontButton.tsx
import React from 'react';
import { A11yManager } from '@a11y-buttons/core';
import '@a11y-buttons/core/src/styles/contrast.css';

interface IncreaseFontButtonProps {
  text?: string;
  style?: React.CSSProperties;
  className?: string;
}

const a11yManager = new A11yManager();

export const IncreaseFontButton: React.FC<IncreaseFontButtonProps> = ({
  text = 'Aumentar Fonte',
  style,
  className
}) => {
  return (
    <button
      onClick={() => a11yManager.increaseFontSize()}
      style={style}
      className={className}
    >
      {text}
    </button>
  );
};

// packages/vue/src/IncreaseFontButton.vue
<template>
  <button :style="style" :class="className" @click="increaseFont">
    {{ text }}
  </button>
</template>

<script setup lang="ts">
import { A11yManager } from '@a11y-buttons/core';
import '@a11y-buttons/core/src/styles/contrast.css';

const props = defineProps({
  text: { type: String, default: 'Aumentar Fonte' },
  style: { type: Object, default: () => ({}) },
  className: { type: String, default: '' }
});

const a11yManager = new A11yManager();

function increaseFont() {
  a11yManager.increaseFontSize();
}
</script>
